[2025-06-04T20:25:58.449+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: community_members_ingestion.fetch_and_store_members_task manual__2025-06-05T03:25:54+07:00 [queued]>
[2025-06-04T20:25:58.479+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: community_members_ingestion.fetch_and_store_members_task manual__2025-06-05T03:25:54+07:00 [queued]>
[2025-06-04T20:25:58.481+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-04T20:25:58.544+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_members_task> on 2025-06-04 20:25:54+00:00
[2025-06-04T20:25:58.552+0000] {standard_task_runner.py:60} INFO - Started process 5059 to run task
[2025-06-04T20:25:58.561+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'community_members_ingestion', 'fetch_and_store_members_task', 'manual__2025-06-05T03:25:54+07:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/api_to_db_dag.py', '--cfg-path', '/tmp/tmpimkuemg_']
[2025-06-04T20:25:58.572+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask fetch_and_store_members_task
[2025-06-04T20:25:58.738+0000] {task_command.py:423} INFO - Running <TaskInstance: community_members_ingestion.fetch_and_store_members_task manual__2025-06-05T03:25:54+07:00 [running]> on host e4f5e6f9211f
[2025-06-04T20:25:58.952+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='community_members_ingestion' AIRFLOW_CTX_TASK_ID='fetch_and_store_members_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T20:25:54+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T03:25:54+07:00'
[2025-06-04T20:26:00.124+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_to_db_dag.py", line 37, in fetch_and_store_members
    records = fetch_all_records(api_url, api_headers)
  File "/opt/airflow/dags/api_to_db_dag.py", line 21, in fetch_all_records
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://app.circle.so/api/admin/v2/members?per_page=1
[2025-06-04T20:26:00.138+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=community_members_ingestion, task_id=fetch_and_store_members_task, execution_date=20250604T202554, start_date=20250604T202558, end_date=20250604T202600
[2025-06-04T20:26:00.158+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task fetch_and_store_members_task (404 Client Error: Not Found for url: https://app.circle.so/api/admin/v2/members?per_page=1; 5059)
[2025-06-04T20:26:00.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T20:26:00.206+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
